# Generated by Django 4.2.2 on 2023-06-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_path',
            field=models.CharField(default='', max_length=250),
        ),
    ]
