# Generated by Django 4.2.2 on 2023-06-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=32)),
                ('cod', models.IntegerField(default=0)),
                ('data_inscr', models.DateField()),
            ],
        ),
    ]
